#!/bin/bash
# autogen-clean.sh
#
# SuperTux
# Copyright (C) 2025 DeltaResero
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#

# ------------------------------------------------------------------------------
# Performs a complete cleanup of build artifacts, configuration files, and
# files generated by Autotools and Jam, resetting the directory to a clean
# state.
# ------------------------------------------------------------------------------

# Exit immediately if a command fails, a variable is unset, or a pipe fails.
set -euo pipefail

# ============================================================================ #
#                         STANDARD BUILD TOOL CLEANUP                          #
# ============================================================================ #

# Attempts to run standard 'clean' targets for Make and Jam.
clean_build_targets() {
    # Try Make targets only if a configured Makefile exists.
    if [ -f Makefile ] && [ -f config.status ]; then
        echo "Found configured Makefile. Attempting deep clean targets..."
        make maintainer-clean || make distclean || make clean
    fi

    # Try Jam clean only if both the source Jamfile and its generated config exist.
    if [ -f Jamfile ] && [ -f Jamconfig ] && command -v jam >/dev/null 2>&1; then
        echo "Found configured Jamfile. Running jam clean..."
        jam clean
    fi
}

# ============================================================================ #
#                          RECURSIVE ARTIFACT REMOVAL                          #
# ============================================================================ #

# Recursively finds and removes generated build artifacts.
remove_recursive_artifacts() {
    echo "Removing recursive configuration and build artifacts..."

    # Remove generated files like Makefiles, templates, object files, etc.
    find . -type f \( \
        -name "Makefile" -o -name "Makefile.in" -o \
        -name "*.pot" -o -name "*.o" -o -name "*.lo" -o -name "*.la" \
    \) -delete

    # Remove generated cache and dependency directories
    find . -type d \( \
        -name ".deps" -o -name ".libs" -o -name "autom4te.cache" \
    \) -exec rm -rf {} +

    # Remove editor backup files (e.g., 'configure~') anywhere in the tree
    find . -type f -name "*~" -delete
}

# ============================================================================ #
#                      BUILD DIRECTORY & ROOT FILE REMOVAL                     #
# ============================================================================ #

# Forcefully clears the contents of the build directory, if it exists.
clear_build_directory() {
    if [ -d "build" ]; then
        echo "Clearing contents of build/ directory..."
        find "build/" -mindepth 1 -delete
    fi
}

# Removes specific root-level files and directories generated by Autotools.
remove_root_files() {
    echo "Removing root-level Autotools configuration files..."

    # CRITICAL: 'Jamfile' is a source file and MUST NOT be deleted.
    # 'Jamconfig' IS a generated file and will be deleted.
    local files_to_remove=(
        "aclocal.m4" "config.guess" "config.sub" "config.status"
        "config.h" "config.h.in" "config.log" "configure"
        "depcomp" "install-sh" "libtool" "ltmain.sh" "missing"
        "mkinstalldirs" "stamp-h" "stamp-h1" "stamp-h.in"
        "ltconfig" "Jamconfig" "Makefile" "supertux"
    )

    # The -f flag prevents errors if the files don't exist.
    rm -rf "${files_to_remove[@]}"
}

# ============================================================================== #
#                                 MAIN EXECUTION                                 #
# ============================================================================== #

echo "Starting full build system cleanup (autogen and build artifacts)..."

clean_build_targets
remove_recursive_artifacts
clear_build_directory
remove_root_files

echo "Cleanup complete."

# EOF
